### ISSUE TITLE
Deep Sleep and display(INKPLATE_3BIT)

### ISSUE THREAD

**Issue by harthenry** [e-radionicacom/Inkplate-Arduino-library#60]
It appears the example Inkplate_Partial_Update_With_Deep_Sleep does not work properly when you change to GrayScale mode via Inkplate display(INKPLATE_3BIT).  The software runs, however, screen update only runs the first time.  There are no updates to the screen while in gray scale mode

**Comment by BornaBiro** [comment]
Partial updates only work in 1 Bit mode, no matter if it's low power mode or normal (run) mode.

You can see a note about that in [partial update example](https://github.com/e-radionicacom/Inkplate-Arduino-library/blob/master/examples/Basic_Inkplate_Functionality/Inkplate_basic_partial_update/Inkplate_basic_partial_update.ino#L10), line 10.

Also, you can see that in the [code](https://github.com/e-radionicacom/Inkplate-Arduino-library/blob/master/src/Inkplate.cpp#L358) of the Inkplate library. If it's selected mode 1 (3 Bit mode), do not update anything.

What you can do is:
- Switch to 1 bit mode and use partial updates
- Continue to use 3 bit mode, but you have to do full screen update every time instead of partial updates.
